local class = require("class")
local blocks = {}

function blocks.testBlockRed()
  local block = class.block.new()
  local canvas = love.graphics.newCanvas(10, 10)
  love.graphics.setCanvas(canvas)
  love.graphics.clear(1, 0, 0, 1)
  love.graphics.setCanvas()
  block:addSurface(class.surface.new(canvas, class.NORTH, class.EAST))
  block:addSurface(class.surface.new(canvas, class.NORTH, class.SOUTH))
  block:addSurface(class.surface.new(canvas, class.NORTH, class.WEST))
  block:addSurface(class.surface.new(canvas, class.NORTH, class.UP))
  block:addSurface(class.surface.new(canvas, class.NORTH, class.DOWN))
  block:addSurface(class.surface.new(canvas, class.EAST, class.NORTH))
  block:addSurface(class.surface.new(canvas, class.EAST, class.SOUTH))
  block:addSurface(class.surface.new(canvas, class.EAST, class.WEST))
  block:addSurface(class.surface.new(canvas, class.EAST, class.UP))
  block:addSurface(class.surface.new(canvas, class.EAST, class.DOWN))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.NORTH))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.EAST))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.WEST))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.UP))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.DOWN))
  block:addSurface(class.surface.new(canvas, class.WEST, class.NORTH))
  block:addSurface(class.surface.new(canvas, class.WEST, class.EAST))
  block:addSurface(class.surface.new(canvas, class.WEST, class.SOUTH))
  block:addSurface(class.surface.new(canvas, class.WEST, class.UP))
  block:addSurface(class.surface.new(canvas, class.WEST, class.DOWN))
  block:addWall(class.wall.new(class.SOUTH))
  block:addWall(class.wall.new(class.NORTH))
  block:addWall(class.wall.new(class.EAST))
  block:addWall(class.wall.new(class.WEST))
  block:addWall(class.wall.new(class.UP))
  block:addWall(class.wall.new(class.DOWN))
  return block
end

function blocks.testBlockBlue()
  local block = class.block.new()
  local canvas = love.graphics.newCanvas(10, 10)
  love.graphics.setCanvas(canvas)
  love.graphics.clear(0, 0, 1, 1)
  love.graphics.setCanvas()
  block:addSurface(class.surface.new(canvas, class.NORTH, class.EAST))
  block:addSurface(class.surface.new(canvas, class.NORTH, class.SOUTH))
  block:addSurface(class.surface.new(canvas, class.NORTH, class.WEST))
  block:addSurface(class.surface.new(canvas, class.NORTH, class.UP))
  block:addSurface(class.surface.new(canvas, class.NORTH, class.DOWN))
  block:addSurface(class.surface.new(canvas, class.EAST, class.NORTH))
  block:addSurface(class.surface.new(canvas, class.EAST, class.SOUTH))
  block:addSurface(class.surface.new(canvas, class.EAST, class.WEST))
  block:addSurface(class.surface.new(canvas, class.EAST, class.UP))
  block:addSurface(class.surface.new(canvas, class.EAST, class.DOWN))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.NORTH))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.EAST))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.WEST))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.UP))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.DOWN))
  block:addSurface(class.surface.new(canvas, class.WEST, class.NORTH))
  block:addSurface(class.surface.new(canvas, class.WEST, class.EAST))
  block:addSurface(class.surface.new(canvas, class.WEST, class.SOUTH))
  block:addSurface(class.surface.new(canvas, class.WEST, class.UP))
  block:addSurface(class.surface.new(canvas, class.WEST, class.DOWN))
  block:addWall(class.wall.new(class.SOUTH))
  block:addWall(class.wall.new(class.NORTH))
  block:addWall(class.wall.new(class.EAST))
  block:addWall(class.wall.new(class.WEST))
  block:addWall(class.wall.new(class.UP))
  block:addWall(class.wall.new(class.DOWN))
  return block
end

return blocks
