local class = require("class")
local blocks = {}

function blocks.testBlockColor(r, g, b, a)
  local block = class.block.new()
  local canvas = love.graphics.newCanvas(10, 10)
  love.graphics.push("all")
  love.graphics.setCanvas(canvas)
  love.graphics.clear(r, g, b, a)
  love.graphics.pop()
  block:addSurface(class.surface.new(canvas, class.NORTH, class.NORTH))
  block:addSurface(class.surface.new(canvas, class.NORTH, class.EAST))
  block:addSurface(class.surface.new(canvas, class.NORTH, class.SOUTH))
  block:addSurface(class.surface.new(canvas, class.NORTH, class.WEST))
  block:addSurface(class.surface.new(canvas, class.NORTH, class.UP))
  block:addSurface(class.surface.new(canvas, class.NORTH, class.DOWN))
  block:addSurface(class.surface.new(canvas, class.EAST, class.NORTH))
  block:addSurface(class.surface.new(canvas, class.EAST, class.EAST))
  block:addSurface(class.surface.new(canvas, class.EAST, class.SOUTH))
  block:addSurface(class.surface.new(canvas, class.EAST, class.WEST))
  block:addSurface(class.surface.new(canvas, class.EAST, class.UP))
  block:addSurface(class.surface.new(canvas, class.EAST, class.DOWN))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.NORTH))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.EAST))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.SOUTH))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.WEST))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.UP))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.DOWN))
  block:addSurface(class.surface.new(canvas, class.WEST, class.NORTH))
  block:addSurface(class.surface.new(canvas, class.WEST, class.EAST))
  block:addSurface(class.surface.new(canvas, class.WEST, class.SOUTH))
  block:addSurface(class.surface.new(canvas, class.WEST, class.WEST))
  block:addSurface(class.surface.new(canvas, class.WEST, class.UP))
  block:addSurface(class.surface.new(canvas, class.WEST, class.DOWN))
  block:addWall(class.wall.new(class.SOUTH))
  block:addWall(class.wall.new(class.NORTH))
  block:addWall(class.wall.new(class.EAST))
  block:addWall(class.wall.new(class.WEST))
  block:addWall(class.wall.new(class.UP))
  block:addWall(class.wall.new(class.DOWN))
  return block
end

function blocks.testSpriteColor(r, g, b, a)
  local block = class.block.new()
  local canvas = love.graphics.newCanvas(100, 100)
  love.graphics.push("all")
  love.graphics.setCanvas(canvas)
  love.graphics.setColor(r, g, b, a)
  love.graphics.circle("fill", 50, 50, 40, 40)
  love.graphics.pop()
  canvas:setFilter("nearest")
  block:addSprite(class.sprite.new(canvas, class.NORTH, 0.4))
  block:addSprite(class.sprite.new(canvas, class.EAST, 0.4))
  block:addSprite(class.sprite.new(canvas, class.SOUTH, 0.4))
  block:addSprite(class.sprite.new(canvas, class.WEST, 0.4))
  block:addWall(class.wall.new(class.SOUTH))
  block:addWall(class.wall.new(class.NORTH))
  block:addWall(class.wall.new(class.EAST))
  block:addWall(class.wall.new(class.WEST))
  block:addWall(class.wall.new(class.UP))
  block:addWall(class.wall.new(class.DOWN))
  return block
end

function blocks.character()
  local block = class.block.new()
  local canvas = love.graphics.newCanvas(100, 100)
  love.graphics.push("all")
  love.graphics.setCanvas(canvas)
  love.graphics.setColor(0.4, 0.6, 0.4, 0.8)
  love.graphics.circle("fill", 50, 50, 40, 40)
  love.graphics.pop()
  canvas:setFilter("nearest")
  block:addSprite(class.sprite.new(canvas, class.NORTH, 0.4))
  block:addSprite(class.sprite.new(canvas, class.EAST, 0.4))
  block:addSprite(class.sprite.new(canvas, class.SOUTH, 0.4))
  block:addSprite(class.sprite.new(canvas, class.WEST, 0.4))
  block:addWall(class.wall.new(class.SOUTH))
  block:addWall(class.wall.new(class.NORTH))
  block:addWall(class.wall.new(class.EAST))
  block:addWall(class.wall.new(class.WEST))
  block:addWall(class.wall.new(class.UP))
  block:addWall(class.wall.new(class.DOWN))
  return block
end

return blocks
