local class = require("class")
local blocks = {}

function blocks.testBlockColor(r, g, b, a)
  local block = class.block.new()
  local canvas = love.graphics.newCanvas(10, 10)
  love.graphics.push("all")
  love.graphics.setCanvas(canvas)
  love.graphics.clear(r, g, b, a)
  love.graphics.pop()
  block:addSurface(class.surface.new(canvas, class.NORTH, class.EAST))
  block:addSurface(class.surface.new(canvas, class.NORTH, class.SOUTH))
  block:addSurface(class.surface.new(canvas, class.NORTH, class.WEST))
  block:addSurface(class.surface.new(canvas, class.NORTH, class.UP))
  block:addSurface(class.surface.new(canvas, class.NORTH, class.DOWN))
  block:addSurface(class.surface.new(canvas, class.EAST, class.NORTH))
  block:addSurface(class.surface.new(canvas, class.EAST, class.SOUTH))
  block:addSurface(class.surface.new(canvas, class.EAST, class.WEST))
  block:addSurface(class.surface.new(canvas, class.EAST, class.UP))
  block:addSurface(class.surface.new(canvas, class.EAST, class.DOWN))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.NORTH))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.EAST))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.WEST))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.UP))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.DOWN))
  block:addSurface(class.surface.new(canvas, class.WEST, class.NORTH))
  block:addSurface(class.surface.new(canvas, class.WEST, class.EAST))
  block:addSurface(class.surface.new(canvas, class.WEST, class.SOUTH))
  block:addSurface(class.surface.new(canvas, class.WEST, class.UP))
  block:addSurface(class.surface.new(canvas, class.WEST, class.DOWN))
  block:addWall(class.wall.new(class.SOUTH))
  block:addWall(class.wall.new(class.NORTH))
  block:addWall(class.wall.new(class.EAST))
  block:addWall(class.wall.new(class.WEST))
  block:addWall(class.wall.new(class.UP))
  block:addWall(class.wall.new(class.DOWN))
  return block
end

function blocks.testSpriteColor(r, g, b, a)
  local block = class.block.new()
  local canvas = love.graphics.newCanvas(100, 100)
  love.graphics.push("all")
  love.graphics.setCanvas(canvas)
  love.graphics.setColor(r, g, b, a)
  love.graphics.circle("fill", 50, 50, 40, 40)
  love.graphics.pop()
  canvas:setFilter("nearest")
  block:addSprite(class.sprite.new(canvas, class.NORTH, 0.4))
  block:addSprite(class.sprite.new(canvas, class.EAST, 0.4))
  block:addSprite(class.sprite.new(canvas, class.SOUTH, 0.4))
  block:addSprite(class.sprite.new(canvas, class.WEST, 0.4))
  block:addWall(class.wall.new(class.SOUTH))
  block:addWall(class.wall.new(class.NORTH))
  block:addWall(class.wall.new(class.EAST))
  block:addWall(class.wall.new(class.WEST))
  block:addWall(class.wall.new(class.UP))
  block:addWall(class.wall.new(class.DOWN))
  return block
end

function blocks.character()
  local block = class.block.new()
  local northCanvas = love.graphics.newCanvas(100, 100)
  local southCanvas = love.graphics.newCanvas(100, 100)
  local eastCanvas = love.graphics.newCanvas(100, 100)
  local westCanvas = love.graphics.newCanvas(100, 100)
  love.graphics.push("all")
  love.graphics.setColor(0.4, 0.6, 0.4, 0.9)
  love.graphics.setCanvas(northCanvas)
  love.graphics.circle("fill", 50, 50, 40)
  love.graphics.setCanvas(southCanvas)
  love.graphics.circle("fill", 50, 50, 40)
  love.graphics.setCanvas(eastCanvas)
  love.graphics.circle("fill", 50, 50, 40)
  love.graphics.setCanvas(westCanvas)
  love.graphics.circle("fill", 50, 50, 40)
  love.graphics.setColor(0.6, 0.6, 0.6, 0.9)
  love.graphics.setCanvas(southCanvas)
  love.graphics.circle("fill", 38, 40, 8)
  love.graphics.circle("fill", 62, 40, 8)
  love.graphics.setCanvas(eastCanvas)
  love.graphics.circle("fill", 62, 40, 8)
  love.graphics.setCanvas(westCanvas)
  love.graphics.circle("fill", 38, 40, 8)
  love.graphics.setColor(0.3, 0.3, 0.3, 0.9)
  love.graphics.setCanvas(southCanvas)
  love.graphics.circle("fill", 38, 42, 4)
  love.graphics.circle("fill", 62, 42, 4)
  love.graphics.setCanvas(eastCanvas)
  love.graphics.circle("fill", 64, 42, 4)
  love.graphics.setCanvas(westCanvas)
  love.graphics.circle("fill", 36, 42, 4)
  love.graphics.pop()
  northCanvas:setFilter("nearest")
  southCanvas:setFilter("nearest")
  eastCanvas:setFilter("nearest")
  westCanvas:setFilter("nearest")
  block:addSprite(class.sprite.new(northCanvas, class.NORTH, 0.4))
  block:addSprite(class.sprite.new(southCanvas, class.SOUTH, 0.4))
  block:addSprite(class.sprite.new(eastCanvas, class.EAST, 0.4))
  block:addSprite(class.sprite.new(westCanvas, class.WEST, 0.4))
  block:setTag("character")
  return block
end

function blocks.lava()
  local block = class.block.new()
  local canvas = love.graphics.newCanvas(100, 100)
  love.graphics.push("all")
  love.graphics.setCanvas(canvas)
  love.graphics.clear(0.7, 0.2, 0.3, 1.0)
  love.graphics.setColor(1.0, 0.6, 0.2, 1.0)
  love.graphics.circle("line", 20, 40, 10)
  love.graphics.circle("line", 70, 30, 10)
  love.graphics.circle("line", 60, 80, 10)
  love.graphics.pop()
  block:addSurface(class.surface.new(canvas, class.NORTH, class.UP))
  block:addSurface(class.surface.new(canvas, class.EAST, class.UP))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.UP))
  block:addSurface(class.surface.new(canvas, class.WEST, class.UP))
  block:setTag("lava")
  return block
end

function blocks.brick()
  local block = class.block.new()
  local canvas = love.graphics.newCanvas(100, 100)
  love.graphics.push("all")
  love.graphics.setCanvas(canvas)
  love.graphics.clear(0.3, 0.1, 0.1, 1.0)
  love.graphics.setLineWidth(5)
  love.graphics.setColor(0.2, 0.1, 0.1, 1.0)
  love.graphics.line(0, 30, 100, 30)
  love.graphics.line(0, 70, 100, 70)
  love.graphics.line(40, 30, 40, 70)
  love.graphics.line(80, 0, 80, 30)
  love.graphics.line(80, 70, 80, 100)
  love.graphics.pop()
  block:addSurface(class.surface.new(canvas, class.NORTH, class.EAST))
  block:addSurface(class.surface.new(canvas, class.NORTH, class.SOUTH))
  block:addSurface(class.surface.new(canvas, class.NORTH, class.WEST))
  block:addSurface(class.surface.new(canvas, class.NORTH, class.UP))
  block:addSurface(class.surface.new(canvas, class.NORTH, class.DOWN))
  block:addSurface(class.surface.new(canvas, class.EAST, class.NORTH))
  block:addSurface(class.surface.new(canvas, class.EAST, class.SOUTH))
  block:addSurface(class.surface.new(canvas, class.EAST, class.WEST))
  block:addSurface(class.surface.new(canvas, class.EAST, class.UP))
  block:addSurface(class.surface.new(canvas, class.EAST, class.DOWN))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.NORTH))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.EAST))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.WEST))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.UP))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.DOWN))
  block:addSurface(class.surface.new(canvas, class.WEST, class.NORTH))
  block:addSurface(class.surface.new(canvas, class.WEST, class.EAST))
  block:addSurface(class.surface.new(canvas, class.WEST, class.SOUTH))
  block:addSurface(class.surface.new(canvas, class.WEST, class.UP))
  block:addSurface(class.surface.new(canvas, class.WEST, class.DOWN))
  block:addWall(class.wall.new(class.SOUTH))
  block:addWall(class.wall.new(class.NORTH))
  block:addWall(class.wall.new(class.EAST))
  block:addWall(class.wall.new(class.WEST))
  block:addWall(class.wall.new(class.UP))
  block:addWall(class.wall.new(class.DOWN))
  return block
end

function blocks.edgetile()
  local block = class.block.new()
  local canvas = love.graphics.newCanvas(100, 100)
  love.graphics.push("all")
  love.graphics.setCanvas(canvas)
  love.graphics.clear(0.1, 0.1, 0.1, 1.0)
  love.graphics.setLineWidth(5)
  love.graphics.setColor(0.2, 0.2, 0.2, 1.0)
  love.graphics.rectangle("fill", 5, 5, 90, 90)
  love.graphics.pop()
  block:addSurface(class.surface.new(canvas, class.NORTH, class.EAST))
  block:addSurface(class.surface.new(canvas, class.NORTH, class.SOUTH))
  block:addSurface(class.surface.new(canvas, class.NORTH, class.WEST))
  block:addSurface(class.surface.new(canvas, class.NORTH, class.UP))
  block:addSurface(class.surface.new(canvas, class.NORTH, class.DOWN))
  block:addSurface(class.surface.new(canvas, class.EAST, class.NORTH))
  block:addSurface(class.surface.new(canvas, class.EAST, class.SOUTH))
  block:addSurface(class.surface.new(canvas, class.EAST, class.WEST))
  block:addSurface(class.surface.new(canvas, class.EAST, class.UP))
  block:addSurface(class.surface.new(canvas, class.EAST, class.DOWN))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.NORTH))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.EAST))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.WEST))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.UP))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.DOWN))
  block:addSurface(class.surface.new(canvas, class.WEST, class.NORTH))
  block:addSurface(class.surface.new(canvas, class.WEST, class.EAST))
  block:addSurface(class.surface.new(canvas, class.WEST, class.SOUTH))
  block:addSurface(class.surface.new(canvas, class.WEST, class.UP))
  block:addSurface(class.surface.new(canvas, class.WEST, class.DOWN))
  block:addWall(class.wall.new(class.SOUTH))
  block:addWall(class.wall.new(class.NORTH))
  block:addWall(class.wall.new(class.EAST))
  block:addWall(class.wall.new(class.WEST))
  block:addWall(class.wall.new(class.UP))
  block:addWall(class.wall.new(class.DOWN))
  return block
end

function blocks.sidetile()
  local block = class.block.new()
  local canvas = love.graphics.newCanvas(100, 100)
  love.graphics.push("all")
  love.graphics.setCanvas(canvas)
  love.graphics.clear(0.1, 0.1, 0.1, 1.0)
  love.graphics.setLineWidth(5)
  love.graphics.setColor(0.2, 0.2, 0.2, 1.0)
  love.graphics.rectangle("fill", 5, 5, 90, 90)
  love.graphics.pop()
  block:addSurface(class.surface.new(canvas, class.NORTH, class.EAST))
  block:addSurface(class.surface.new(canvas, class.NORTH, class.SOUTH))
  block:addSurface(class.surface.new(canvas, class.NORTH, class.WEST))
  block:addSurface(class.surface.new(canvas, class.EAST, class.NORTH))
  block:addSurface(class.surface.new(canvas, class.EAST, class.SOUTH))
  block:addSurface(class.surface.new(canvas, class.EAST, class.WEST))
  block:addSurface(class.surface.new(canvas, class.EAST, class.DOWN))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.NORTH))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.EAST))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.WEST))
  block:addSurface(class.surface.new(canvas, class.WEST, class.NORTH))
  block:addSurface(class.surface.new(canvas, class.WEST, class.EAST))
  block:addSurface(class.surface.new(canvas, class.WEST, class.SOUTH))
  block:addWall(class.wall.new(class.SOUTH))
  block:addWall(class.wall.new(class.NORTH))
  block:addWall(class.wall.new(class.EAST))
  block:addWall(class.wall.new(class.WEST))
  block:addWall(class.wall.new(class.UP))
  block:addWall(class.wall.new(class.DOWN))
  return block
end

function blocks.toptile()
  local block = class.block.new()
  local canvas = love.graphics.newCanvas(100, 100)
  love.graphics.push("all")
  love.graphics.setCanvas(canvas)
  love.graphics.clear(0.1, 0.1, 0.1, 1.0)
  love.graphics.setLineWidth(5)
  love.graphics.setColor(0.2, 0.2, 0.2, 1.0)
  love.graphics.rectangle("fill", 5, 5, 90, 90)
  love.graphics.pop()
  block:addSurface(class.surface.new(canvas, class.NORTH, class.UP))
  block:addSurface(class.surface.new(canvas, class.EAST, class.UP))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.UP))
  block:addSurface(class.surface.new(canvas, class.WEST, class.UP))
  block:addSurface(class.surface.new(canvas, class.NORTH, class.DOWN))
  block:addSurface(class.surface.new(canvas, class.EAST, class.DOWN))
  block:addSurface(class.surface.new(canvas, class.SOUTH, class.DOWN))
  block:addSurface(class.surface.new(canvas, class.WEST, class.DOWN))
  block:addWall(class.wall.new(class.SOUTH))
  block:addWall(class.wall.new(class.NORTH))
  block:addWall(class.wall.new(class.EAST))
  block:addWall(class.wall.new(class.WEST))
  block:addWall(class.wall.new(class.UP))
  block:addWall(class.wall.new(class.DOWN))
  return block
end

function blocks.orb()
  local block = class.block.new()
  local canvas = love.graphics.newCanvas(100, 100)
  love.graphics.push("all")
  love.graphics.setCanvas(canvas)
  love.graphics.setColor(0.5, 0.4, 1.0, 0.6)
  love.graphics.circle("fill", 50, 50, 50)
  love.graphics.setColor(0.6, 0.3, 1.0, 0.4)
  love.graphics.circle("fill", 50, 50, 30)
  love.graphics.pop()
  canvas:setFilter("nearest")
  block:addSprite(class.sprite.new(canvas, class.NORTH, 0.4))
  block:addSprite(class.sprite.new(canvas, class.SOUTH, 0.4))
  block:addSprite(class.sprite.new(canvas, class.EAST, 0.4))
  block:addSprite(class.sprite.new(canvas, class.WEST, 0.4))
  block:setTag("orb")
  return block
end

return blocks
